variables:
  URL: "https://hakatools.hakalab.com/hakatools/"
  TIME_IMPLICITY: "10"
  EXECUTION_TYPE: "localhost"
  BROWSER: "chrome"
  EXECUTION_PARALLEL: "false"
  SELENIUM_HUB_IP: "34.176.173.129"
  WIDTH_RESOLUTION: "1300"
  HEIGHT_RESOLUTION: "900"
  BROWSER_VERSION_SELENIUM: "100.0"
  EXECUTE_ALLURE: "true"
  SAVE_REPORT_ALLURE: "true"
  CLEAN_EXTRAS_REPORT_ALLURE: "false"


stages:
  - sonarqube-check
  - test
  - deploy

check.sonar:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_TOKEN: "$SONAR_TOKEN"
    SONAR_HOST_URL: "http://34.95.239.169:9000"
    GIT_DEPTH: 0
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - demo_nadro

test.chrome:
  stage: test
  image: python:3.9
  services:
    - name: selenium/standalone-chrome:latest
  before_script:
    - apt -y update
    - apt -y upgrade
    - apt-get -y install default-jre
    - apt -y install wget
    - apt-get -y update
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - cd helper/vendor
    - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.6/allure-commandline-2.13.6.zip
    - unzip allure-commandline-2.13.6.zip
    - rm allure-commandline-2.13.6.zip
    - cd ../../
    - behave -f allure_behave.formatter:AllureFormatter -o reporte -t "@formulario_basico"
    - mv ./report ./report_chrome
  artifacts:
#    when: always
    expire_in: 1 hrs
    paths:
      - report_chrome/
  only:
    - demo_nadro

pages:
  stage: deploy
  script:
    - mkdir public
    - mv ./report_chrome ./public/
  dependencies:
    - test.chrome
  artifacts:
    paths:
      - public
  only:
    - demo_nadro
